name: publish

on:
  push:
    branches:
      - "main"

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
        with:
          ref: ${{ github.ref }}
      - run: sed -n 3p ./package.json
      - uses: "actions/setup-node@v2"
        with:
          node-version: '14'
      - name: "version bump"
        uses: "phips28/gh-action-bump-version@master"
        with:
          tag-prefix: ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: sed -n 3p ./package.json
  
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 12
  #     - run: npm ci
  #     - run: npm run prod:test

  # publish:
  #   needs: [bump, test]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         ref: master
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 12
  #     - run: npm ci
  #     - run: npm run prod:build
  #     - uses: w9jds/firebase-action@master
  #       with:
  #         args: deploy
  #       env:
  #         PROJECT_ID: arc-prod-41999
  #         FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
